### PR TITLE
Better default settings drupal.org/node/3177185

### PR DESCRIPTION
**Pull request by joejoseph00**
Optimize default URL alias settings for French
https://www.drupal.org/project/wxt/issues/3177185
credit to smulvih2

### CODE REVIEW

**Comment by joejoseph00** [comment]
this should be sufficient right?
```
            "drupal/pathauto": {
                "Better defaults for pathauto to support french.":
                "https://www.drupal.org/files/issues/2020-10-15/pathauto-config-install-3177185-3.patch"
            },
```

**Comment by sylus** [comment]
Yup I merged it here:

https://github.com/drupalwxt/wxt/commit/6dc0a667564abe7575c5f569331466d0b32af883

The P.R. was not passing because logic in github action wasn't taking into account right var for Pull Requests, should be fixed now but i manually merged ftm.

**Comment by joejoseph00** [comment]
hmm, in that commit the composer.json is not included, rather you're including the config yml into wxt , the patch appeared to add config yml to config/install/pathauto.settings.yml  , I guess either way if it works including the config yml right into wxt rather than into the pathauto module then that's fine also.
as long as it works :)
Thanks again!

**Comment by joejoseph00** [comment]
hmm, ya pathauto module I think was brought into core right?  some confusion over that.    Either way I think you did this correctly by adding the yml into wxt

**Pull request closed without merging**
