### PR TITLE
Bump all versions of wet-boew/wet-boew

### PR DESCRIPTION
**Pull request by RabiaSajjad**
This updates all mentions of wet-boew to version v4.0.28.1

We still need to update the lock file with a `composer update` commands, but we were having problems, so starting here.

Here is the error output from `composer update`:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wet-boew/wet-boew 4.0.27 exists as wet-boew/wet-boew[v4.0.28] but these are rejected by your constraint.
  Problem 2
    - The requested package wet-boew/theme-wet-boew 4.0.27 exists as wet-boew/theme-wet-boew[v4.0.28] but these are rejected by your constraint.
  Problem 3
    - The requested package wet-boew/theme-base 4.0.27 exists as wet-boew/theme-base[v4.0.28] but these are rejected by your constraint.
  Problem 4
    - The requested package wet-boew/theme-gc-intranet 4.0.27 exists as wet-boew/theme-gc-intranet[v4.0.28] but these are rejected by your constraint.
  Problem 5
    - The requested package wet-boew/theme-gcwu-fegc 4.0.27 exists as wet-boew/theme-gcwu-fegc[v4.0.28] but these are rejected by your constraint.
  Problem 6
    - The requested package wet-boew/theme-gcweb 4.0.27 exists as wet-boew/theme-gcweb[v4.0.28] but these are rejected by your constraint.
  Problem 7
    - The requested package wet-boew/theme-ogpl 4.0.27 exists as wet-boew/theme-ogpl[v4.0.28] but these are rejected by your constraint.
  Problem 8
    - Installation request for drupal/wxt_library 1.2 -> satisfiable by drupal/wxt_library[1.2.0].
    - drupal/wxt_library 1.2.0 requires wet-boew/wet-boew 4.0.27 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

### CODE REVIEW

**Comment by zachomedia** [comment]
@RabiaSajjad Thank you for the pull request. We've been a bit behind on updating wet-beow. 

Note however, that only the gcweb and wet-boew themes have a 4.0.28 / 4.0.28.1 release. The latest available version for the other themes is 4.0.27. (See https://github.com/wet-boew/themes-cdn/issues/4). We can do like the Drupal 7 distro, and only update the gcweb and wet-boew themes.

The errors you're seeing can be attributed to [wxt_library](https://github.com/drupalwxt/wxt_library) module also needing to be updated for the newer wet-boew packages.

**Comment by nathanpw** [comment]
I believe @jeffdavidgordon is also working on this as part of open-data in https://github.com/open-data/wxt/tree/update-wetboew

**Comment by RabiaSajjad** [comment]
@zachomedia is there a timeline for updating wxt_library?

@nathanpw Sorry for the confusion. Git settings were old in my machine. I was the one making changes.

**Comment by zachomedia** [comment]
@RabiaSajjad No set timeline, but I'm hoping to do another WxT release in the next week since we have some updates to the wxt_bootstrap module to release.

**Comment by zachomedia** [comment]
Closing in favour of #112

**Pull request closed without merging**
